apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: envoy
    app.kubernetes.io/instance: mirror-proxy
    app.kubernetes.io/name: mirror-proxy
    app.kubernetes.io/version: v1.23.1
  name: mirror-proxy
  namespace: mirror
spec:
  ports:
  - name: admin
    port: 9901
    targetPort: 9901
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: envoy
    app.kubernetes.io/instance: mirror-proxy
    app.kubernetes.io/name: mirror-proxy
